routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('companies', 'CompaniesController');
Route::resource('employee', 'EmployeeController');

app/Companies.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use App\URL;

class Companies extends Model
{
    protected $table = 'companies';
    protected $fillable = ['nama', 'email', 'website', 'logo'];

    public function getLogoAttribute($value)
    {
        return asset('storage/company/'.$value);
    }
}

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table = 'employees';
    protected $fillable = ['nama', 'company', 'email'];

    public function companies()
    {
        return $this->belongsTo(Companies::class, 'company', 'id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Companies;
use App\Repository\CompaniesRepository;
use Illuminate\Support\Facades\Storage;

class CompaniesController extends Controller
{
    protected $comp;

    public function __construct(CompaniesRepository $comp)
    {
        $this->comp = $comp;
    }

    public function index()
    {
        return view('company.index')
            ->withTitle('Data Perusahaan')
            ->withData($this->comp->getPaginate(5));
    }

    public function create()
    {
        return view('company.create')
            ->withData(new Companies)
            ->withTitle('Tambah Data Perusahaan');
    }

    public function store(Request $request)
    {
        $this->comp->validation($request);
        
        $upload = $this->comp->uploadImage($request);
        if($upload != false){
            $data = [
                'nama' => $request->nama,
                'email' => $request->email,
                'website' => $request->website,
                'logo' => $upload
            ];
            $save = $this->comp->saveUpdate($data);
        }

        if($save == true){
            return redirect()->route('companies.index')->with('success', 'Data berhasil disimpan');
        }else{
            return redirect()->route('companies.index')->with('fail', 'Data gagal disimpan');
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        return view('company.edit')
            ->withTitle('Edit Data Perusahaan')
            ->withData($this->comp->getById($id));
    }

    public function update(Request $request, $id)
    {

        $data = [
            'nama' => $request->nama,
            'email' => $request->email,
            'website' => $request->website
        ];

        $this->comp->validation($request, $request->check);
        
        if($request->hasFile('logo')) {
            $upload = $this->comp->uploadImage($request);
            $data = [
                'nama' => $request->nama,
                'email' => $request->email,
                'website' => $request->website,
                'logo' => $upload
            ];
        }

        $update = $this->comp->saveUpdate($data, $id);
        if($update == true){
            return redirect()->route('companies.index')->with('success', 'Data berhasil diupdate');
        }else{
            return redirect()->route('companies.index')->with('fail', 'Data gagal diupdate');
        }

    }

    public function destroy($id)
    {
        $delete = Companies::where('id', $id)->delete();
        if($delete){
            return redirect()->route('companies.index')->with('success', 'Data berhasil dihapus');
        }else{
            return redirect()->route('companies.index')->with('fail', 'Data gagal dihapus');
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;
use App\Companies;
use App\Repository\EmployeeRepository;

class EmployeeController extends Controller
{
    protected $emp;

    public function __construct(EmployeeRepository $emp)
    {
        $this->emp = $emp;
    }

    public function index()
    {
        return view('employee.index')
            ->withTitle('Data Karyawan')
            ->withData($this->emp->getPaginate(5));
    }

    public function create()
    {
        $company = new Companies();
        return view('employee.create')
            ->withData(new Employee)
            ->withCompany($company->all())
            ->withTitle('Tambah Data Karyawan');
    }

    public function store(Request $request)
    {
        $this->emp->validation($request);
        
        $data = [
            'nama' => $request->nama,
            'email' => $request->email,
            'company' => $request->company,
        ];
        $save = $this->emp->saveUpdate($data);

        if($save == true){
            return redirect()->route('employee.index')->with('success', 'Data berhasil disimpan');
        }else{
            return redirect()->route('employee.index')->with('fail', 'Data gagal disimpan');
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $company = new Companies();
        return view('employee.edit')
            ->withTitle('Edit Data Karyawan')
            ->withData($this->emp->getById($id))
            ->withCompany($company->all());
    }

    public function update(Request $request, $id)
    {
        $this->emp->validation($request);
        
        $data = [
            'nama' => $request->nama,
            'email' => $request->email,
            'company' => $request->company,
        ];
        $save = $this->emp->saveUpdate($data, $id);

        if($save == true){
            return redirect()->route('employee.index')->with('success', 'Data berhasil diperbaharui');
        }else{
            return redirect()->route('employee.index')->with('fail', 'Data gagal diperbaharui');
        }
    }

    public function destroy($id)
    {
        $delete = Employee::where('id', $id)->delete();
        if($delete){
            return redirect()->route('employee.index')->with('success', 'Data berhasil dihapus');
        }else{
            return redirect()->route('employee.index')->with('fail', 'Data gagal dihapus');
        }
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/company/_form.blade.php
@csrf
<div class="form-group">
    <label for="nama" class="text-md-right">{{ __('Nama Perusahaan') }}</label>
    <input id="nama" type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ old('nama', $data->nama) }}" autofocus>
    @error('nama')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
    @enderror
</div>

<div class="form-group">
    <label for="email" class="text-md-right">{{ __('Email') }}</label>
    <input id="email" type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email', $data->email) }}">
    @error('email')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
    @enderror
</div>

<div class="form-group">
    <label for="website" class="text-md-right">{{ __('Website') }}</label>
    <input id="website" type="text" class="form-control @error('website') is-invalid @enderror" name="website" value="{{ old('website', $data->website) }}">
    @error('website')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
    @enderror
</div>

<div class="form-group">
    <label for="logo" class="text-md-right">{{ __('Logo Perusahaan') }}</label>
    <input id="logo" type="file" name="logo" class="form-control @error('logo') is-invalid @enderror">
    <input type="hidden" value="{{ $data->id }}" name="check">
    @error('logo')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
    @enderror
</div>

<div class="form-group mb-0">
    <button type="submit" class="btn btn-primary">
        {{ $buttonText }}
    </button>
</div>

resources/views/company/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container py-3">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        Tambah Data Perusahaan
                        <a href="{{ route('companies.index') }}" class="btn btn-danger btn-sm float-right">kembali</a>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('companies.store') }}" enctype="multipart/form-data">
                            @include ("company._form", ['buttonText' => "Simpan"])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container py-3">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        Edit Data Perusahaan
                        <a href="{{ route('companies.index') }}" class="btn btn-danger btn-sm float-right">kembali</a>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('companies.update', $data->id) }}" enctype="multipart/form-data">
                            @method('PUT')
                            @include ("company._form", ['buttonText' => "Edit"])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/company/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Data Perusahaan
                        <a href="{{ route('companies.create') }}" class="btn btn-success btn-sm float-right">tambah</a>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <td>No.</td>
                                    <td>Logo</td>
                                    <td>Nama Perusahaan</td>
                                    <td>Email</td>
                                    <td>Website</td>
                                    <td width="5%">Aksi</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($data as $key => $comp)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>
                                        <img src="{{ $comp->logo }}" class="img-fluid img-thumbnail" width="120">
                                    </td>
                                    <td>{{ $comp->nama }}</td>
                                    <td>{{ $comp->email }}</td>
                                    <td><a href="http://{{ $comp->website }}" target="_blank">{{ $comp->website }}</a></td>
                                    <td>
                                        <a href="{{ route('companies.edit', $comp->id ) }}" class="btn btn-primary btn-sm">edit</a>
                                        <form method="POST" action="{{ route('companies.destroy', $comp->id) }}" class="my-1">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm">hapus</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <div class="float-right">
                            {{ $data->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/employee/_form.blade.php
@csrf
<div class="form-group">
    <label for="nama" class="text-md-right">{{ __('Nama Karyawan') }}</label>
    <input id="nama" type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ old('nama', $data->nama) }}" autofocus>
    @error('nama')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
    @enderror
</div>

<div class="form-group">
    <label for="email" class="text-md-right">{{ __('Email') }}</label>
    <input id="email" type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email', $data->email) }}">
    @error('email')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
    @enderror
</div>

<div class="form-group">
    <label for="company" class="text-md-right">{{ __('Perusahaan') }}</label>
    <select name="company" id="company" class="form-control @error('company') is-invalid @enderror">
        <option value="">Pilih Perusahaan</option>
        @foreach($company as $comp)
            <option value="{{ $comp->id }}" {{ old('company', $data->company) == $comp->id ? "selected":"" }}>{{ $comp->nama }}</option>
        @endforeach
    </select>
    @error('company')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
    @enderror
</div>

<div class="form-group mb-0">
    <button type="submit" class="btn btn-primary">
        {{ $buttonText }}
    </button>
</div>

resources/views/employee/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container py-3">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        Tambah Data Karyawan
                        <a href="{{ route('employee.index') }}" class="btn btn-danger btn-sm float-right">kembali</a>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('employee.store') }}">
                            @include ("employee._form", ['buttonText' => "Simpan"])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container py-3">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        Edit Data Karyawan
                        <a href="{{ route('employee.index') }}" class="btn btn-danger btn-sm float-right">kembali</a>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('employee.update', $data->id) }}" enctype="multipart/form-data">
                            @method('PUT')
                            @include ("employee._form", ['buttonText' => "Edit"])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/employee/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Data Karyawan
                        <a href="{{ route('employee.create') }}" class="btn btn-success btn-sm float-right">tambah</a>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <td>No.</td>
                                    <td>Nama Karyawan</td>
                                    <td>Perusahaan</td>
                                    <td>Email</td>
                                    <td width="5%">Aksi</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($data as $key => $emp)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $emp->nama }}</td>
                                    <td>{{ $emp->companies['nama'] }}</td>
                                    <td>{{ $emp->email }}</td>
                                    <td>
                                        <a href="{{ route('employee.edit', $emp->id ) }}" class="btn btn-primary btn-sm">edit</a>
                                        <form method="POST" action="{{ route('employee.destroy', $emp->id) }}" class="my-1">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm">hapus</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <div class="float-right">
                            {{ $data->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div class="container py-2">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Selamat Datang !
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>
        @if(isset($title))
            {{ $title }}
        @else
            Login
        @endif
    </title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    
    @auth
        @include('layouts.menu')
    @endauth

    <div id="app">
        <main>
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/menu.blade.php
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand font-weight-bold" href="{{ url('/') }}">
                PT Transisi Teknologi Mandiri
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active"><a href="{{ route('companies.index') }}" class="nav-link">DATA PERUSAHAAN</a></li>
                    <li class="nav-item"><a href="{{ route('employee.index') }}" class="nav-link">DATA KARYAWAN</a></li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container py-3">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>	
                    <strong>{{ $message }}</strong>
                </div>
                @endif

                @if ($message = Session::get('fail'))
                <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>	
                    <strong>{{ $message }}</strong>
                </div>
                @endif
            </div>
        </div>
    </div>